# https://www.youtube.com/watch?v=WnlX7w4lHvM&t=9s

version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181


# [kafka container 접속 이후 토픽 생성]
# $ docker exec -it {container-name} /bin/sh
# $ ./bin/kafka-topics.sh --create --zookeeper zookeeper:2181 --replication-factor 1 --partitions 2 --topic {topic-name}

# [kafka 토픽 리스트 조회]
# $ ./bin/kafka-topics.sh --list --zookeeper zookeeper:2181
# $ container-topic

# [kafka 토픽 내 메시지 조회]
# $ ./bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic {topic-name} --from-beginning


