
server:
  port: 8091

kafka:
  consumer:
    container-topic: 'container-topic'
    employee-topic: 'employee-topic'
    bootstrapServers:
      - 'localhost:9092'
    groupId: 'container-group'
    offset: 'latest'
    max-poll-records: 50