
server:
  port: 8091

kafka:
  consumer:
    props:
      bootstrapServers:
        - 'localhost:9092'
      groupId: 'springboot-consumer-group'
      offset: 'latest'
      max-poll-records: 25

    # container message
    container:
      topic: 'container-topic'
      container-factory: 'containerContainerFactory'

    # employee message
    employee:
      topic: 'employee-topic'
      container-factory: 'employeeContainerFactory'